/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as heroSol from "./Hero.sol";
export type { heroSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { Auction } from "./Auction";
export type { FLPCrowdSale } from "./FLPCrowdSale";
export type { HeroMarketplace } from "./HeroMarketplace";
export type { USDT } from "./USDT";
export type { Vault } from "./Vault";
